## Initialize Fiddler Client

In [1]:
import fiddler as fdl
import logging

# True for logging debug message 
verbose = True

if verbose:
    logging.basicConfig(level=logging.DEBUG)

client = fdl.FiddlerApi(verbose=verbose)

INFO:root:url =http://host.docker.internal:4100
INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/project/get/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/project/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2'}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): host.docker.internal:4100
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/project/get/onebox HTTP/1.1" 400 95
INFO:root:response: {"errors": {"": "None is not of type 'object'"}, "message": "Input payload validation failed"}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/project/get/onebox
Request:
  url: http://host.docker.internal:4100/v1/project/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2'}
INFO:root:running api call as GET request
to http://host.docker.internal:4100/list_projects/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/list_projects/onebox
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "GET /list_projects/onebox HTTP/1.1" 200 126059
INFO:root:response: {
  "status": "SUCCESS",
  "result": {
    "id": "onebox",
    "projects": [
      {
        "id": "bank_churn",
        "name": "bank_churn",
        "models": [
          {
            "name": "Bank Customer Churn Prediction",
            "input-type": "structured",
            "model-task": "binary_classification",
            "inputs": [
              {
                "column-name": "CreditScore",
                "data-type": "int"
              },
              {
                "column-name": "Geography",
                "data-type": "category",
                "possible-values": [
                  "France",
                  "Germany",
                  "Spain"
                ]
              },
              {
                "column-name": "Gender",
                "data-type": "category",
                "possible-values": [
                  "Female",
                  "Male"
                ]
              },
              {
                "column-name": "Age",
                "data-type": "int"
              },
              {
                "column-name": "Tenure",
                "data-type": "int"
              },
              {
                "column-name": "Balance",
                "data-type": "float"
              },
              {
                "column-name": "NumOfProducts",
                "data-type": "int"
              },
              {
                "column-name": "HasCrCard",
                "data-type": "category",
                "possible-values": [
                  "Yes",
                  "No"
                ]
              },
              {
                "column-name": "IsActiveMember",
                "data-type": "category",
                "possible-values": [
                  "Yes",
                  "No"
                ]
              },
              {
                "column-name": "EstimatedSalary",
                "data-type": "float"
              }
            ],
            "outputs": [
              {
                "column-name": "probability_churned",
                "data-type": "float"
              }
            ],
            "datasets": [
              "bank_churn"
            ],
            "targets": [
              {
                "column-name": "Churned",
                "data-type": "category",
                "possible-values": [
                  "Churned",
                  "Not Churned"
                ]
              }
            ],
            "description": "Predict whether a customer will stay or churn",
            "class-labels": [
              1,
              0
            ],
            "algorithm": "Random Forest",
            "id": "bank_churn"
          }
        ]
      },
      {
        "id": "heart_disease",
        "name": "heart_disease",
        "models": [
          {
            "name": " model",
            "input-type": "structured",
            "model-task": "binary_classification",
            "inputs": [
              {
                "column-name": "age",
                "data-type": "int"
              },
              {
                "column-name": "sex",
                "data-type": "int"
              },
              {
                "column-name": "trestbps",
                "data-type": "int"
              },
              {
                "column-name": "chol",
                "data-type": "int"
              },
              {
                "column-name": "fbs",
                "data-type": "int"
              },
              {
                "column-name": "thalach",
                "data-type": "int"
              },
              {
                "column-name": "exang",
                "data-type": "int"
              },
              {
                "column-name": "oldpeak",
                "data-type": "float"
              },
              {
                "column-name": "slope",
                "data-type": "int"
              }
            ],
            "outputs": [
              {
                "column-name": "predicted_target",
                "data-type": "float"
              }
            ],
            "datasets": [
              "heart_disease"
            ],
            "targets": [
              {
                "column-name": "target",
                "data-type": "int"
              }
            ],
            "id": "heart_disease"
          }
        ]
      },
      {
        "id": "imdb_rnn",
        "name": "imdb_rnn",
        "models": [
          {
            "name": "BiLSTM SavedModel",
            "input-type": "text",
            "model-task": "binary_classification",
            "inputs": [
              {
                "column-name": "sentence",
                "data-type": "str"
              }
            ],
            "outputs": [
              {
                "column-name": "sentiment",
                "data-type": "float"
              }
            ],
            "datasets": [
              "imdb_rnn"
            ],
            "targets": [
              {
                "column-name": "polarity",
                "data-type": "bool"
              }
            ],
            "description": "This is a bidirectional LSTM model saved as a TF SavedModel.",
            "framework": "tensorflow",
            "class-labels": [
              "negative",
              "positive"
            ],
            "version": 1,
            "algorithm": "BiLSTM",
            "id": "imdb_rnn"
          },
          {
            "name": "BiLSTM SavedModel",
            "input-type": "text",
            "model-task": "binary_classification",
            "inputs": [
              {
                "column-name": "sentence",
                "data-type": "str"
              }
            ],
            "outputs": [
              {
                "column-name": "sentiment",
                "data-type": "float"
              }
            ],
            "datasets": [
              "imdb_rnn"
            ],
            "targets": [
              {
                "column-name": "polarity",
                "data-type": "bool"
              }
            ],
            "description": "This is a bidirectional LSTM model saved as a TF SavedModel.",
            "framework": "tensorflow",
            "class-labels": [
              "negative",
              "positive"
            ],
            "version": 1,
            "algorithm": "BiLSTM",
            "id": "imdb_rnn_test"
          }
        ]
      },
      {
        "id": "iris_classification",
        "name": "iris_classification",
        "models": [
          {
            "name": "Iris Species Classification",
            "input-type": "structured",
            "model-task": "multiclass_classification",
            "inputs": [
              {
                "column-name": "sepal length (cm)",
                "data-type": "float"
              },
              {
                "column-name": "sepal width (cm)",
                "data-type": "float"
              },
              {
                "column-name": "petal length (cm)",
                "data-type": "float"
              },
              {
                "column-name": "petal width (cm)",
                "data-type": "float"
              }
            ],
            "outputs": [
              {
                "column-name": "setosa_likelihood",
                "data-type": "float"
              },
              {
                "column-name": "versicolor_likelihood",
                "data-type": "float"
              },
              {
                "column-name": "virginica_likelihood",
                "data-type": "float"
              }
            ],
            "datasets": [
              "iris"
            ],
            "targets": [
              {
                "column-name": "species",
                "data-type": "category",
                "possible-values": [
                  0,
                  1,
                  2
                ]
              }
            ],
            "description": "This model predicts which species an iris is based upon its physical properties",
            "framework": "scikit-learn 0.20.2",
            "version": 1.23,
            "training_id": "UTC-2019-02-06",
            "algorithm": "L2-Regularized Multinomial Logistic Regression",
            "hyperparameters": {
              "standardization": "false"
            },
            "annotations": [
              "Annotation 1",
              "Annotation 2",
              "Annotation 3"
            ],
            "id": "iris"
          }
        ]
      },
      {
        "id": "lending",
        "name": "lending",
        "models": [
          {
            "name": "All-variable Logistic Regression Loan Status Predictor",
            "input-type": "structured",
            "model-task": "binary_classification",
            "inputs": [
              {
                "column-name": "loan_amnt",
                "data-type": "float"
              },
              {
                "column-name": "int_rate",
                "data-type": "float"
              },
              {
                "column-name": "sub_grade",
                "data-type": "category",
                "possible-values": [
                  "A3",
                  "F4",
                  "B5",
                  "B2",
                  "D5",
                  "B4",
                  "E2",
                  "G3",
                  "A2",
                  "G1",
                  "D3",
                  "B3",
                  "B1",
                  "D4",
                  "D1",
                  "A1",
                  "A5",
                  "A4",
                  "F3",
                  "E4",
                  "G5",
                  "F2",
                  "C5",
                  "C2",
                  "E5",
                  "C1",
                  "E1",
                  "C3",
                  "F1",
                  "F5",
                  "D2",
                  "C4",
                  "G4",
                  "E3",
                  "G2"
                ]
              },
              {
                "column-name": "emp_length",
                "data-type": "category",
                "possible-values": [
                  "< 1 year",
                  "1 year",
                  "2 years",
                  "9 years",
                  "10+ years",
                  "4 years",
                  "7 years",
                  "5 years",
                  "6 years",
                  "3 years",
                  "8 years"
                ]
              },
              {
                "column-name": "home_ownership",
                "data-type": "category",
                "possible-values": [
                  "OTHER",
                  "OWN",
                  "NONE",
                  "RENT",
                  "MORTGAGE",
                  "ANY"
                ]
              },
              {
                "column-name": "annual_inc",
                "data-type": "float"
              },
              {
                "column-name": "purpose",
                "data-type": "category",
                "possible-values": [
                  "debt_consolidation",
                  "moving",
                  "other",
                  "home_improvement",
                  "renewable_energy",
                  "house",
                  "credit_card",
                  "small_business",
                  "major_purchase",
                  "vacation",
                  "wedding",
                  "medical",
                  "car"
                ]
              },
              {
                "column-name": "addr_state",
                "data-type": "category",
                "possible-values": [
                  "OH",
                  "IN",
                  "KY",
                  "SD",
                  "NM",
                  "FL",
                  "VT",
                  "OK",
                  "NH",
                  "MS",
                  "PA",
                  "NY",
                  "MI",
                  "UT",
                  "AR",
                  "MD",
                  "IL",
                  "NV",
                  "IA",
                  "TX",
                  "RI",
                  "CO",
                  "CA",
                  "SC",
                  "MN",
                  "WA",
                  "WV",
                  "AK",
                  "GA",
                  "ID",
                  "DC",
                  "NC",
                  "HI",
                  "WY",
                  "CT",
                  "WI",
                  "DE",
                  "TN",
                  "MO",
                  "AZ",
                  "AL",
                  "VA",
                  "LA",
                  "MA",
                  "NE",
                  "OR",
                  "MT",
                  "ME",
                  "KS",
                  "NJ"
                ]
              },
              {
                "column-name": "dti",
                "data-type": "float"
              },
              {
                "column-name": "delinq_2yrs",
                "data-type": "float"
              },
              {
                "column-name": "fico_range_low",
                "data-type": "float"
              },
              {
                "column-name": "inq_last_6mths",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_last_delinq",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_last_record",
                "data-type": "float"
              },
              {
                "column-name": "open_acc",
                "data-type": "float"
              },
              {
                "column-name": "pub_rec",
                "data-type": "float"
              },
              {
                "column-name": "revol_bal",
                "data-type": "float"
              },
              {
                "column-name": "revol_util",
                "data-type": "float"
              },
              {
                "column-name": "total_acc",
                "data-type": "float"
              },
              {
                "column-name": "collections_12_mths_ex_med",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_last_major_derog",
                "data-type": "float"
              },
              {
                "column-name": "acc_now_delinq",
                "data-type": "float"
              },
              {
                "column-name": "tot_coll_amt",
                "data-type": "float"
              },
              {
                "column-name": "tot_cur_bal",
                "data-type": "float"
              },
              {
                "column-name": "total_rev_hi_lim",
                "data-type": "float"
              },
              {
                "column-name": "acc_open_past_24mths",
                "data-type": "float"
              },
              {
                "column-name": "avg_cur_bal",
                "data-type": "float"
              },
              {
                "column-name": "bc_open_to_buy",
                "data-type": "float"
              },
              {
                "column-name": "bc_util",
                "data-type": "float"
              },
              {
                "column-name": "chargeoff_within_12_mths",
                "data-type": "float"
              },
              {
                "column-name": "delinq_amnt",
                "data-type": "float"
              },
              {
                "column-name": "mo_sin_old_rev_tl_op",
                "data-type": "float"
              },
              {
                "column-name": "mo_sin_rcnt_rev_tl_op",
                "data-type": "float"
              },
              {
                "column-name": "mo_sin_rcnt_tl",
                "data-type": "float"
              },
              {
                "column-name": "mort_acc",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_recent_bc",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_recent_inq",
                "data-type": "float"
              },
              {
                "column-name": "mths_since_recent_revol_delinq",
                "data-type": "float"
              },
              {
                "column-name": "num_accts_ever_120_pd",
                "data-type": "float"
              },
              {
                "column-name": "num_actv_bc_tl",
                "data-type": "float"
              },
              {
                "column-name": "num_actv_rev_tl",
                "data-type": "float"
              },
              {
                "column-name": "num_bc_sats",
                "data-type": "float"
              },
              {
                "column-name": "num_bc_tl",
                "data-type": "float"
              },
              {
                "column-name": "num_il_tl",
                "data-type": "float"
              },
              {
                "column-name": "num_op_rev_tl",
                "data-type": "float"
              },
              {
                "column-name": "num_rev_accts",
                "data-type": "float"
              },
              {
                "column-name": "num_rev_tl_bal_gt_0",
                "data-type": "float"
              },
              {
                "column-name": "num_sats",
                "data-type": "float"
              },
              {
                "column-name": "num_tl_120dpd_2m",
                "data-type": "float"
              },

INFO:root:API call to http://host.docker.internal:4100/list_projects/onebox succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": {
      "id": "onebox",
      "projects": [
        {
          "id": "bank_churn",
          "name": "bank_churn",
          "models": [
            {
              "name": "Bank Customer Churn Prediction",
              "input-type": "structured",
              "model-task": "binary_classification",
              "inputs": [
                {
                  "column-name": "CreditScore",
                  "data-type": "int"
                },
                {
                  "column-name": "Geography",
                  "data-type": "category",
                  "possible-values": [
                    "France",
                    "Germany",
                    "Spain"
                  ]
                },
                {
                  "column-name": "Gender",
                  "data-type": "category",
                  "possible-values": [
                    "Female",
                    "Male"
                  ]
                },
                {
                  "column-name": "Age",
                  "data-type": "int"
                },
                {
                  "column-name": "Tenure",
                  "data-type": "int"
                },
                {
                  "column-name": "Balance",
                  "data-type": "float"
                },
                {
                  "column-name": "NumOfProducts",
                  "data-type": "int"
                },
                {
                  "column-name": "HasCrCard",
                  "data-type": "category",
                  "possible-values": [
                    "Yes",
                    "No"
                  ]
                },
                {
                  "column-name": "IsActiveMember",
                  "data-type": "category",
                  "possible-values": [
                    "Yes",
                    "No"
                  ]
                },
                {
                  "column-name": "EstimatedSalary",
                  "data-type": "float"
                }
              ],
              "outputs": [
                {
                  "column-name": "probability_ch
Request:
  url: http://host.docker.internal:4100/list_projects/onebox
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

## Upload dataset

In [4]:
import pandas as pd

dataset_id = 'titanic'
target = 'survived'

client.delete_dataset(dataset_id)

if dataset_id in client.list_datasets():
    df = client.get_dataset(dataset_id)['train']
    df_schema = client.get_dataset_info(dataset_id)
else:
    df = pd.read_csv('/app/fiddler_samples/samples/datasets/titanic/train.csv')
    df[target] = df[target].astype(str)
    df_schema = fdl.DatasetInfo.from_dataframe(df, max_inferred_cardinality=1000)
    upload_result = client.upload_dataset(
        dataset={'train': df}, 
        dataset_id=dataset_id,
        info=df_schema)

INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/dataset/delete/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "dataset_id": "titanic"
  }
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/dataset/delete/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
DEBUG:urllib3.connectionpool:Resetting dropped connection: host.docker.internal
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/dataset/delete/onebox HTTP/1.1" 400 95
INFO:root:response: {"errors": {"": "None is not of type 'object'"}, "message": "Input payload validation failed"}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/dataset/delete/onebox
Request:
  url: http://host.docker.internal:4100/v1/dataset/delete/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
INFO:root:running api call as POST request
to http://host.docker.internal:4100/dataset_delete/onebox/titanic
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/dataset_delete/onebox/titanic
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /dataset_delete/onebox/titanic HTTP/1.1" 200 64
INFO:root:response: {
  "status": "SUCCESS",
  "result": "Dataset deleted titanic"
}
INFO:root:API call to http://host.docker.internal:4100/dataset_delete/onebox/titanic succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": "Dataset deleted titanic"
  }
Request:
  url: http://host.docker.internal:4100/dataset_delete/onebox/titanic
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4'}

INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/dataset/get/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/dataset/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/dataset/get/onebox HTTP/1.1" 400 95
INFO:root:response: {"errors": {"": "None is not of type 'object'"}, "message": "Input payload validation failed"}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/dataset/get/onebox
Request:
  url: http://host.docker.internal:4100/v1/dataset/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2'}
INFO:root:running api call as GET request
to http://host.docker.internal:4100/list_datasets/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/list_datasets/onebox
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "GET /list_datasets/onebox HTTP/1.1" 200 217
INFO:root:response: {
  "status": "SUCCESS",
  "result": [
    "20news",
    "bank_churn",
    "heart_disease",
    "imdb_rnn",
    "iris",
    "p2p_loans",
    "winequality",
    "wine_quality",
    "loan_status",
    "p2p_loans1"
  ]
}
INFO:root:API call to http://host.docker.internal:4100/list_datasets/onebox succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": [
      "20news",
      "bank_churn",
      "heart_disease",
      "imdb_rnn",
      "iris",
      "p2p_loans",
      "winequality",
      "wine_quality",
      "loan_status",
      "p2p_loans1"
    ]
  }
Request:
  url: http://host.docker.internal:4100/list_datasets/onebox
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

INFO:root:[train] dataset upload: writing csv to /tmp/tmpo8b9s6ow/train.csv
INFO:root:[titanic] dataset upload: uploading csv
INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/dataset/upload/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "dataset_name": "titanic",
    "split_test": false,
    "dataset_info": {
      "dataset": {
        "name": "",
        "columns": [
          {
            "column-name": "pclass",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 1,
            "value-range-max": 3
          },
          {
            "column-name": "survived",
            "data-type": "category",
            "possible-values": [
              "0",
              "1"
            ],
            "is-nullable": false
          },
          {
            "column-name": "name",
            "data-type": "str",
            "is-nullable": false
          },
          {
            "column-name": "sex",
            "data-type": "category",
            "possible-values": [
              "female",
              "male"
            ],
            "is-nullable": false
          },
          {
            "column-name": "age",
            "data-type": "float",
            "is-nullable": true,
            "value-range-min": 0.1667,
            "value-range-max": 80.0
          },
          {
            "column-name": "sibsp",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 8
          },
          {
            "column-name": "parch",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 9
          },
          {
            "column-name": "ticket",
            "data-type": "category",
            "possible-values": [
              "110152",
              "110413",
              "110465",
              "110469",
              "110489",
              "110564",
              "110813",
              "111163",
              "111240",
              "111320",
              "111361",
              "111369",
              "111426",
              "111427",
              "111428",
              "112050",
              "112051",
              "112052",
              "112053",
              "112058",
              "112059",
              "112277",
              "112377",
              "112378",
              "112379",

DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/dataset/upload/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '129966', 'Content-Type': 'multipart/form-data; boundary=b582df191af93b378562f420108844e2'}

DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/dataset/upload/onebox HTTP/1.1" 500 37
INFO:root:response: {"message": "Internal Server Error"}

DEBUG:root:API call failed.
Error message: Internal Server Error
Endpoint: http://host.docker.internal:4100/v1/dataset/upload/onebox
Request:
  url: http://host.docker.internal:4100/v1/dataset/upload/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '129966', 'Content-Type': 'multipart/form-data; boundary=b582df191af93b378562f420108844e2'}
INFO:root:running api call as POST request
to http://host.docker.internal:4100/dataset_upload/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "dataset_name": "titanic",
    "split_test": false,
    "dataset_info": {
      "dataset": {
        "name": "",
        "columns": [
          {
            "column-name": "pclass",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 1,
            "value-range-max": 3
          },
          {
            "column-name": "survived",
            "data-type": "category",
            "possible-values": [
              "0",
              "1"
            ],
            "is-nullable": false
          },
          {
            "column-name": "name",
            "data-type": "str",
            "is-nullable": false
          },
          {
            "column-name": "sex",
            "data-type": "category",
            "possible-values": [
              "female",
              "male"
            ],
            "is-nullable": false
          },
          {
            "column-name": "age",
            "data-type": "float",
            "is-nullable": true,
            "value-range-min": 0.1667,
            "value-range-max": 80.0
          },
          {
            "column-name": "sibsp",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 8
          },
          {
            "column-name": "parch",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 9
          },
          {
            "column-name": "ticket",
            "data-type": "category",
            "possible-values": [
              "110152",
              "110413",
              "110465",
              "110469",
              "110489",
              "110564",
              "110813",
              "111163",
              "111240",
              "111320",
              "111361",
              "111369",
              "111426",
              "111427",
              "111428",
              "112050",
              "112051",
              "112052",
              "112053",
              "112058",
              "112059",
              "112277",
              "112377",
              "112378",
              "112379",

DEBUG:root:Request:
  url: http://host.docker.internal:4100/dataset_upload/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '129966', 'Content-Type': 'multipart/form-data; boundary=6983184ea09cc4a47c4927c9980c88c9'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /dataset_upload/onebox HTTP/1.1" 200 41662
INFO:root:response: {
  "status": "SUCCESS",
  "result": {
    "dataset": {
      "name": "",
      "columns": [
        {
          "column-name": "pclass",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 1,
          "value-range-max": 3
        },
        {
          "column-name": "survived",
          "data-type": "category",
          "possible-values": [
            "0",
            "1"
          ],
          "is-nullable": false
        },
        {
          "column-name": "name",
          "data-type": "str",
          "is-nullable": false
        },
        {
          "column-name": "sex",
          "data-type": "category",
          "possible-values": [
            "female",
            "male"
          ],
          "is-nullable": false
        },
        {
          "column-name": "age",
          "data-type": "float",
          "is-nullable": true,
          "value-range-min": 0.1667,
          "value-range-max": 80.0
        },
        {
          "column-name": "sibsp",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 0,
          "value-range-max": 8
        },
        {
          "column-name": "parch",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 0,
          "value-range-max": 9
        },
        {
          "column-name": "ticket",
          "data-type": "category",
          "possible-values": [
            "110152",
            "110413",
            "110465",
            "110469",
            "110489",
            "110564",
            "110813",
            "111163",
            "111240",
            "111320",
            "111361",
            "111369",
            "111426",
            "111427",
            "111428",
            "112050",
            "112051",
            "112052",
            "112053",
            "112058",
            "112059",
            "112277",
            "112377",
            "112378",
            "112379",
            "112901",
            "113028",
            "113038",
            "113043",
            "113044",
            "113050",
            "113051",
            "113054",
            "113055",
            "113056",
            "113059",
            "113501",
            "113503",
            "113505",
            "113509",
            "113510",
            "113514",
            "113572",
            "113760",
            "113767",
            "113773",
            "113776",
            "113778",
            "113780",
            "113781",
            "113783",
            "113784",
            "113786",
            "113787",
            "113788",
            "113789",
            "113790",
            "113791",
            "113792",
            "113794",
            "113795",
            "113796",
            "113798",
            "113800",
            "113801",
            "113803",
            "113804",
            "113806",
            "113807",
            "11668",
            "11751",
            "11752",
            "11753",
            "11755",
            "11765",
            "11767",
            "11769",
            "11770",
            "11771",
            "11774",
            "11778",
            "11813",
            "11967",
            "1222",
            "12233",
            "12460",
            "12749",
            "13049",
            "13050",
            "13213",
            "13214",
            "13236",
            "13502",
            "13507",
            "13508",
            "13509",
            "13567",
            "13568",
            "13695",
            "13905",
            "14311",
            "14312",
            "14313",
            "14973",
            "1601",
            "16966",
            "16988",
            "17421",
            "17453",
            "17463",
            "17464",
            "17465",
            "17466",
            "17474",
            "17475",
            "17764",
            "17765",
            "17770",
            "19877",
            "19924",
            "19928",
            "19943",
            "19947",
            "19950",
            "19952",
            "19972",
            "19988",
            "19996",
            "2003",
            "211535",
            "211536",
            "21228",
            "21332",
            "21440",
            "218629",
            "219533",
            "220367",
            "220844",
            "220845",
            "2223",
            "223596",
            "226593",
            "226875",
            "228414",
            "229236",
            "230080",
            "230136",
            "230433",
            "230434",
            "231919",
            "231945",
            "233478",
            "233639",
            "233734",
            "233866",
            "234360",
            "234604",
            "234686",
            "234818",
            "235509",
            "236171",
            "236852",
            "236853",
            "236854",
            "237216",
            "237249",
            "237393",
            "237442",
            "237565",
            "237668",
            "237670",
            "237671",
            "237734",
            "237735",
            "237736",
            "237789",
            "237798",
            "239059",
            "239853",
            "239854",
            "239855",
            "239856",
            "239865",
            "240261",
            "240276",
            "24065",
            "240929",
            "24160",
            "242963",
            "243847",
            "243880",
            "244252",
            "244270",
            "244278",
            "244310",
            "244346",
            "244358",
            "244360",
            "244361",
            "244367",
            "244368",
            "244373",
            "248659",
            "248698",
            "248706",
            "248723",
            "248726",
            "248727",
            "248731",
            "248733",
            "248734",
            "248738",
            "248740",
            "248744",
            "248746",
            "248747",
            "250643",
            "250644",
            "250646",
            "250647",
            "250648",
            "250649",
            "250650",
            "250651",
            "250652",
            "250653",
            "250655",
            "2543",
            "2620",
            "2621",
            "2622",
            "2623",
            "2624",
            "2625",
            "2626",
            "2627",
            "2628",
            "2629",
            "2631",
            "26360",
            "2641",
            "2647",
            "2648",
            "2649",
            "2650",
            "2651",
            "2652",
            "2653",
            "2654",
            "2655",
            "2656",
            "2657",
            "2658",
            "2659",
            "2660",
            "2661",
            "2662",
            "2663",
            "2664",
            "2665",
            "2666",
            "2667",
            "2668",
            "2669",
            "2670",
            "26707",
            "2671",
            "2672",
            "2673",
            "2674",
            "2675",
            "2676",
            "2677",
            "2678",
            "2679",
            "2680",
            "2681",
            "2682",
            "2683",
            "2684",
            "2685",
            "2686",
            "2687",
            "2688",
            "2689",
            "2690",
            "2691",
            "2692",
            "2693",
            "2694",
            "2695",
            "2696",
            "2697",
            "2698",
            "2699",
            "2700",
            "27042",
            "27267",
            "27849",
            "28004",
            "28034",
            "28133",
            "28134",
            "28206",
            "28213",
            "28220",
            "28221",
            "28228",
            "28403",
            "28404",
            "28424",
            "28425",
            "28551",
            "28664",
            "28665",
            "28666",
            "29011",
            "2908",
            "29103",
            "29104",
            "29105",
            "29106",
            "29107",
            "29108",
            "2926",
            "29750",
            "29751",
            "3101264",
            "3101265",
            "3101266",
            "3101267",
            "3101276",
            "3101277",
            "3101278",
            "3101281",
            "3101295",
            "3101296",
            "3101297",
            "3101298",
            "31027",
            "31028",
            "312991",
            "312992",
            "312993",
            "31418",
            "315037",
            "315082",
            "315083",
            "315084",
            "315085",
            "315086",
            "315087",
            "315088",
            "315089",
            "315090",
            "315091",
            "315092",
            "315093",
            "315094",
            "315095",
            "315096",
            "315097",
            "315098",
            "315151",
            "315152",
            "315153",
            "315154",
            "32302",
            "323592",
            "323951",
            "324669",
            "329944",
            "330844",
            "330877",
            "330909",
            "330910",
            "330911",
            "330919",
            "330920",
            "330923",
            "330924",
            "330931",
            "330932",
            "330935",
            "330958",
            "330959",
            "330963",
            "330968",
            "330971",
            "330972",
            "330979",
            "330980",
            "334912",
            "334914",
            "334915",
            "335097",
            "335432",
            "335677",
            "33638",
            "336439",
            "3410",
            "3411",
            "341826",
            "34218",
            "342441",
            "342684",
            "342712",
            "342826",
            "343095",
            "343120",
            "343271",
            "343275",
            "343276",
            "345364",
            "345498",
            "345501",
            "345572",
            "345763",
            "345764",
            "345765",
            "345767",
            "345768",
            "345769",
            "345770",
            "345771",
            "345773",
            "345774",
            "345775",
            "345777",
            "345778",
            "345779",
            "345780",
            "345781",
            "345783",
            "3460",
            "3470",
            "347054",
            "347060",
            "347061",
            "347062",
            "347063",
            "347064",
            "347065",
            "347066",
            "347067",
            "347068",
            "347069",
            "347070",
            "347071",
            "347072",
            "347073",
            "347074",
            "347075",
            "347076",
            "347077",
            "347078",
            "347079",
            "347080",
            "347081",
            "347082",
            "347083",
            "347085",
            "347086",
            "347087",
            "347088",
            "347089",
            "347090",
            "347091",
            "3474",
            "347464",
            "347465",
            "347466",
            "347467",
            "347468",
            "347469",
            "347470",
            "347471",
            "347742",
            "347743",
            "348121",
            "348122",
            "348123",
            "348124",
            "348125",
            "349201",
            "349202",
            "349203",
            "349204",
            "349205",
            "349206",
            "349207",
            "349208",
            "349209",
            "349210",
            "349211",
            "349212",
            "349213",
            "349214",
            "349215",
            "349216",
            "349217",
            "349218",
            "349219",
            "349220",
            "349221",
            "349222",
            "349223",
            "349224",
            "349225",
            "349226",
            "349227",
            "349228",
            "349229",
            "349230",
            "349231",
            "349232",
            "349233",
            "349234",
            "349235",
            "349236",
            "349237",
            "349238",
            "349239",
            "349240",
            "349241",
            "349242",
            "349243",
            "349244",
            "349245",
            "349246",
            "349247",
            "349248",
            "349249",
            "349250",
            "349251",
            "349252",
            "349253",
            "349254",
            "349255",
            "349256",
            "349257",
            "349909",
            "349910",
            "349911",
            "349912",
            "350025",
            "350026",
            "350029",
            "350033",
            "350034",
            "350035",
            "350036",
            "350042",
            "350043",
            "350045",
            "350046",
            "350047",
            "350048",
            "350050",
            "350052",
            "350053",
            "350054",
            "350060",
            "350403",
            "350404",
            "350405",
            "350406",
            "350407",
            "350408",
            "350409",
            "350410",
            "350416",
            "350417",
            "35273",
            "35281",
            "35851",
            "35852",
            "358585",
            "359306",
            "359309",
            "36209",
            "362316",
            "363272",
            "363291",
            "363294",
            "363592",
            "363611",
            "364498",
            "364499",
            "364500",
            "364506",
            "364511",
            "364512",
            "364516",
            "364846",
            "364848",
            "364849",
            "364850",
            "364851",
            "364856",
            "364858",
            "364859",
            "365222",
            "365226",
            "365235",
            "365237",
            "36568",
            "366713",
            "367226",
            "367227",
            "367228",
            "367229",
            "367230",
            "367231",
            "367232",
            "367655",
            "368323",
            "368364",
            "368402",
            "368573",
            "36864",
            "36865",
            "36866",
            "368702",
            "368703",
            "368783",
            "36928",
            "36947",
            "36963",
            "36967",
            "36973",
            "3701",
            "370129",
            "370365",
            "370368",
            "370369",
            "370370",
            "370371",
            "370372",
            "370373",
            "370374",
            "370375",
            "370376",
            "370377",
            "371060",
            "371109",
            "371110",
            "371362",
            "372622",
            "373450",
            "374746",
            "374887",
            "374910",
            "376563",
            "376564",
            "376566",
            "382649",
            "382650",
            "382651",
            "382652",
            "382653",
            "383121",
            "383123",
            "383162",
            "384461",
            "386525",
            "392091",
            "392092",
            "392095",
            "392096",
            "394140",
            "4133",
            "4134",
            "4135",
            "4136",
            "4137",
            "4138",
            "4579",
            "54636",
            "5727",
            "65303",
            "65304",
            "65305",
            "65306",
            "6563",
            "680",
            "693",

INFO:root:API call to http://host.docker.internal:4100/dataset_upload/onebox succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": {
      "dataset": {
        "name": "",
        "columns": [
          {
            "column-name": "pclass",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 1,
            "value-range-max": 3
          },
          {
            "column-name": "survived",
            "data-type": "category",
            "possible-values": [
              "0",
              "1"
            ],
            "is-nullable": false
          },
          {
            "column-name": "name",
            "data-type": "str",
            "is-nullable": false
          },
          {
            "column-name": "sex",
            "data-type": "category",
            "possible-values": [
              "female",
              "male"
            ],
            "is-nullable": false
          },
          {
            "column-name": "age",
            "data-type": "float",
            "is-nullable": true,
            "value-range-min": 0.1667,
            "value-range-max": 80.0
          },
          {
            "column-name": "sibsp",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 8
          },
          {
            "column-name": "parch",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 9
          },
          {
            "column-name": "ticket",
            "data-type": "category",
            "possible-values": [
              "110152",
              "110413",
              "110465",
              "110469",
              "110489",
              "110564",
              "110813",
              "111163",
              "111240",
              "111320",
              "111361",
              "111369",
              "111426",
              "111427",
              "111428",
              "112050",
              "112051",
              "112052",
              "112053",
              "112058",
              "112059",
              "112277",
              "112377",
              "112378",
              "112379",
              "112901",
              "113028",

Request:
  url: http://host.docker.internal:4100/dataset_upload/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '129966', 'Content-Type': 'multipart/form-data; boundary=6983184ea09cc4a47c4927c9980c88c9'}

INFO:root:[titanic] dataset upload: triggering import of dataset
INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/dataset/import/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "dataset_id": "titanic"
  }
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/dataset/import/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/dataset/import/onebox HTTP/1.1" 400 95
INFO:root:response: {"errors": {"": "None is not of type 'object'"}, "message": "Input payload validation failed"}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/dataset/import/onebox
Request:
  url: http://host.docker.internal:4100/v1/dataset/import/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
INFO:root:running api call as GET request
to http://host.docker.internal:4100/import_dataset/onebox/titanic
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/import_dataset/onebox/titanic
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "GET /import_dataset/onebox/titanic HTTP/1.1" 200 217
INFO:root:response: {
  "status": "SUCCESS",
  "result": {
    "row_count": 1309,
    "col_count": 14,
    "log": [
      "Importing dataset titanic",
      "Creating table for titanic",
      "Importing data file: train.csv"
    ]
  }
}
INFO:root:API call to http://host.docker.internal:4100/import_dataset/onebox/titanic succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": {
      "row_count": 1309,
      "col_count": 14,
      "log": [
        "Importing dataset titanic",
        "Creating table for titanic",
        "Importing data file: train.csv"
      ]
    }
  }
Request:
  url: http://host.docker.internal:4100/import_dataset/onebox/titanic
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

In [3]:
## Generate and write model info

In [5]:
import pathlib
import shutil
import pickle
import yaml
from fiddler import ModelTask

project_id = 'tutorial'
model_id = 'titanic'

train_input = df.drop(columns=[target])
feature_columns = list(train_input.columns)

model_info = fdl.ModelInfo.from_dataset_info(
    dataset_info=client.get_dataset_info(dataset_id),
    target=target, 
    features=feature_columns,
    model_task=ModelTask.BINARY_CLASSIFICATION,
    display_name='Titanic',
    description='Predict likelihood of survival'
)

# create temp dir
model_dir = pathlib.Path(model_id)
shutil.rmtree(model_dir, ignore_errors=True)
model_dir.mkdir()

# save model schema
with open(model_dir / 'model.yaml', 'w') as yaml_file:
    yaml.dump({'model': model_info.to_dict()}, yaml_file)
    
model_info

INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/dataset/get/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "dataset_id": "titanic"
  }
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/dataset/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
DEBUG:urllib3.connectionpool:Resetting dropped connection: host.docker.internal
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/dataset/get/onebox HTTP/1.1" 400 95
INFO:root:response: {"errors": {"": "None is not of type 'object'"}, "message": "Input payload validation failed"}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/dataset/get/onebox
Request:
  url: http://host.docker.internal:4100/v1/dataset/get/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '25'}
INFO:root:running api call as GET request
to http://host.docker.internal:4100/dataset_schema/onebox/titanic
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload None
DEBUG:root:Request:
  url: http://host.docker.internal:4100/dataset_schema/onebox/titanic
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "GET /dataset_schema/onebox/titanic HTTP/1.1" 200 41662
INFO:root:response: {
  "status": "SUCCESS",
  "result": {
    "dataset": {
      "name": "",
      "columns": [
        {
          "column-name": "pclass",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 1,
          "value-range-max": 3
        },
        {
          "column-name": "survived",
          "data-type": "category",
          "possible-values": [
            "0",
            "1"
          ],
          "is-nullable": false
        },
        {
          "column-name": "name",
          "data-type": "str",
          "is-nullable": false
        },
        {
          "column-name": "sex",
          "data-type": "category",
          "possible-values": [
            "female",
            "male"
          ],
          "is-nullable": false
        },
        {
          "column-name": "age",
          "data-type": "float",
          "is-nullable": true,
          "value-range-min": 0.1667,
          "value-range-max": 80.0
        },
        {
          "column-name": "sibsp",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 0,
          "value-range-max": 8
        },
        {
          "column-name": "parch",
          "data-type": "int",
          "is-nullable": false,
          "value-range-min": 0,
          "value-range-max": 9
        },
        {
          "column-name": "ticket",
          "data-type": "category",
          "possible-values": [
            "110152",
            "110413",
            "110465",
            "110469",
            "110489",
            "110564",
            "110813",
            "111163",
            "111240",
            "111320",
            "111361",
            "111369",
            "111426",
            "111427",
            "111428",
            "112050",
            "112051",
            "112052",
            "112053",
            "112058",
            "112059",
            "112277",
            "112377",
            "112378",
            "112379",
            "112901",
            "113028",
            "113038",
            "113043",
            "113044",
            "113050",
            "113051",
            "113054",
            "113055",
            "113056",
            "113059",
            "113501",
            "113503",
            "113505",
            "113509",
            "113510",
            "113514",
            "113572",
            "113760",
            "113767",
            "113773",
            "113776",
            "113778",
            "113780",
            "113781",
            "113783",
            "113784",
            "113786",
            "113787",
            "113788",
            "113789",
            "113790",
            "113791",
            "113792",
            "113794",
            "113795",
            "113796",
            "113798",
            "113800",
            "113801",
            "113803",
            "113804",
            "113806",
            "113807",
            "11668",
            "11751",
            "11752",
            "11753",
            "11755",
            "11765",
            "11767",
            "11769",
            "11770",
            "11771",
            "11774",
            "11778",
            "11813",
            "11967",
            "1222",
            "12233",
            "12460",
            "12749",
            "13049",
            "13050",
            "13213",
            "13214",
            "13236",
            "13502",
            "13507",
            "13508",
            "13509",
            "13567",
            "13568",
            "13695",
            "13905",
            "14311",
            "14312",
            "14313",
            "14973",
            "1601",
            "16966",
            "16988",
            "17421",
            "17453",
            "17463",
            "17464",
            "17465",
            "17466",
            "17474",
            "17475",
            "17764",
            "17765",
            "17770",
            "19877",
            "19924",
            "19928",
            "19943",
            "19947",
            "19950",
            "19952",
            "19972",
            "19988",
            "19996",
            "2003",
            "211535",
            "211536",
            "21228",
            "21332",
            "21440",
            "218629",
            "219533",
            "220367",
            "220844",
            "220845",
            "2223",
            "223596",
            "226593",
            "226875",
            "228414",
            "229236",
            "230080",
            "230136",
            "230433",
            "230434",
            "231919",
            "231945",
            "233478",
            "233639",
            "233734",
            "233866",
            "234360",
            "234604",
            "234686",
            "234818",
            "235509",
            "236171",
            "236852",
            "236853",
            "236854",
            "237216",
            "237249",
            "237393",
            "237442",
            "237565",
            "237668",
            "237670",
            "237671",
            "237734",
            "237735",
            "237736",
            "237789",
            "237798",
            "239059",
            "239853",
            "239854",
            "239855",
            "239856",
            "239865",
            "240261",
            "240276",
            "24065",
            "240929",
            "24160",
            "242963",
            "243847",
            "243880",
            "244252",
            "244270",
            "244278",
            "244310",
            "244346",
            "244358",
            "244360",
            "244361",
            "244367",
            "244368",
            "244373",
            "248659",
            "248698",
            "248706",
            "248723",
            "248726",
            "248727",
            "248731",
            "248733",
            "248734",
            "248738",
            "248740",
            "248744",
            "248746",
            "248747",
            "250643",
            "250644",
            "250646",
            "250647",
            "250648",
            "250649",
            "250650",
            "250651",
            "250652",
            "250653",
            "250655",
            "2543",
            "2620",
            "2621",
            "2622",
            "2623",
            "2624",
            "2625",
            "2626",
            "2627",
            "2628",
            "2629",
            "2631",
            "26360",
            "2641",
            "2647",
            "2648",
            "2649",
            "2650",
            "2651",
            "2652",
            "2653",
            "2654",
            "2655",
            "2656",
            "2657",
            "2658",
            "2659",
            "2660",
            "2661",
            "2662",
            "2663",
            "2664",
            "2665",
            "2666",
            "2667",
            "2668",
            "2669",
            "2670",
            "26707",
            "2671",
            "2672",
            "2673",
            "2674",
            "2675",
            "2676",
            "2677",
            "2678",
            "2679",
            "2680",
            "2681",
            "2682",
            "2683",
            "2684",
            "2685",
            "2686",
            "2687",
            "2688",
            "2689",
            "2690",
            "2691",
            "2692",
            "2693",
            "2694",
            "2695",
            "2696",
            "2697",
            "2698",
            "2699",
            "2700",
            "27042",
            "27267",
            "27849",
            "28004",
            "28034",
            "28133",
            "28134",
            "28206",
            "28213",
            "28220",
            "28221",
            "28228",
            "28403",
            "28404",
            "28424",
            "28425",
            "28551",
            "28664",
            "28665",
            "28666",
            "29011",
            "2908",
            "29103",
            "29104",
            "29105",
            "29106",
            "29107",
            "29108",
            "2926",
            "29750",
            "29751",
            "3101264",
            "3101265",
            "3101266",
            "3101267",
            "3101276",
            "3101277",
            "3101278",
            "3101281",
            "3101295",
            "3101296",
            "3101297",
            "3101298",
            "31027",
            "31028",
            "312991",
            "312992",
            "312993",
            "31418",
            "315037",
            "315082",
            "315083",
            "315084",
            "315085",
            "315086",
            "315087",
            "315088",
            "315089",
            "315090",
            "315091",
            "315092",
            "315093",
            "315094",
            "315095",
            "315096",
            "315097",
            "315098",
            "315151",
            "315152",
            "315153",
            "315154",
            "32302",
            "323592",
            "323951",
            "324669",
            "329944",
            "330844",
            "330877",
            "330909",
            "330910",
            "330911",
            "330919",
            "330920",
            "330923",
            "330924",
            "330931",
            "330932",
            "330935",
            "330958",
            "330959",
            "330963",
            "330968",
            "330971",
            "330972",
            "330979",
            "330980",
            "334912",
            "334914",
            "334915",
            "335097",
            "335432",
            "335677",
            "33638",
            "336439",
            "3410",
            "3411",
            "341826",
            "34218",
            "342441",
            "342684",
            "342712",
            "342826",
            "343095",
            "343120",
            "343271",
            "343275",
            "343276",
            "345364",
            "345498",
            "345501",
            "345572",
            "345763",
            "345764",
            "345765",
            "345767",
            "345768",
            "345769",
            "345770",
            "345771",
            "345773",
            "345774",
            "345775",
            "345777",
            "345778",
            "345779",
            "345780",
            "345781",
            "345783",
            "3460",
            "3470",
            "347054",
            "347060",
            "347061",
            "347062",
            "347063",
            "347064",
            "347065",
            "347066",
            "347067",
            "347068",
            "347069",
            "347070",
            "347071",
            "347072",
            "347073",
            "347074",
            "347075",
            "347076",
            "347077",
            "347078",
            "347079",
            "347080",
            "347081",
            "347082",
            "347083",
            "347085",
            "347086",
            "347087",
            "347088",
            "347089",
            "347090",
            "347091",
            "3474",
            "347464",
            "347465",
            "347466",
            "347467",
            "347468",
            "347469",
            "347470",
            "347471",
            "347742",
            "347743",
            "348121",
            "348122",
            "348123",
            "348124",
            "348125",
            "349201",
            "349202",
            "349203",
            "349204",
            "349205",
            "349206",
            "349207",
            "349208",
            "349209",
            "349210",
            "349211",
            "349212",
            "349213",
            "349214",
            "349215",
            "349216",
            "349217",
            "349218",
            "349219",
            "349220",
            "349221",
            "349222",
            "349223",
            "349224",
            "349225",
            "349226",
            "349227",
            "349228",
            "349229",
            "349230",
            "349231",
            "349232",
            "349233",
            "349234",
            "349235",
            "349236",
            "349237",
            "349238",
            "349239",
            "349240",
            "349241",
            "349242",
            "349243",
            "349244",
            "349245",
            "349246",
            "349247",
            "349248",
            "349249",
            "349250",
            "349251",
            "349252",
            "349253",
            "349254",
            "349255",
            "349256",
            "349257",
            "349909",
            "349910",
            "349911",
            "349912",
            "350025",
            "350026",
            "350029",
            "350033",
            "350034",
            "350035",
            "350036",
            "350042",
            "350043",
            "350045",
            "350046",
            "350047",
            "350048",
            "350050",
            "350052",
            "350053",
            "350054",
            "350060",
            "350403",
            "350404",
            "350405",
            "350406",
            "350407",
            "350408",
            "350409",
            "350410",
            "350416",
            "350417",
            "35273",
            "35281",
            "35851",
            "35852",
            "358585",
            "359306",
            "359309",
            "36209",
            "362316",
            "363272",
            "363291",
            "363294",
            "363592",
            "363611",
            "364498",
            "364499",
            "364500",
            "364506",
            "364511",
            "364512",
            "364516",
            "364846",
            "364848",
            "364849",
            "364850",
            "364851",
            "364856",
            "364858",
            "364859",
            "365222",
            "365226",
            "365235",
            "365237",
            "36568",
            "366713",
            "367226",
            "367227",
            "367228",
            "367229",
            "367230",
            "367231",
            "367232",
            "367655",
            "368323",
            "368364",
            "368402",
            "368573",
            "36864",
            "36865",
            "36866",
            "368702",
            "368703",
            "368783",
            "36928",
            "36947",
            "36963",
            "36967",
            "36973",
            "3701",
            "370129",
            "370365",
            "370368",
            "370369",
            "370370",
            "370371",
            "370372",
            "370373",
            "370374",
            "370375",
            "370376",
            "370377",
            "371060",
            "371109",
            "371110",
            "371362",
            "372622",
            "373450",
            "374746",
            "374887",
            "374910",
            "376563",
            "376564",
            "376566",
            "382649",
            "382650",
            "382651",
            "382652",
            "382653",
            "383121",
            "383123",
            "383162",
            "384461",
            "386525",
            "392091",
            "392092",
            "392095",
            "392096",
            "394140",
            "4133",
            "4134",
            "4135",
            "4136",
            "4137",
            "4138",
            "4579",
            "54636",
            "5727",
            "65303",
            "65304",
            "65305",
            "65306",
            "6563",
            "680",
            "693",
            "694",
            "695",
            "7266",
            "7267",
            "7534",
            "7538",
            "7540",
            "7545",
            "7546",
            "7548",
            "7552",
            "7553",
            "7598",
            "7935",
            "8471",
            "8475",
            "9232",
            "9234",
            "A. 2. 39186",
            "A./5. 2152",
            "A./5. 3235",
            "A./5. 3338",
            "A.5. 11206",
            "A.5. 18509",
            "A.5. 3236",
            "A/4 31416",
            "A/4 45380",
            "A/4 48871",
            "A/4 48873",
            "A/4. 20589",
            "A/4. 34244",
            "A/4. 39886",
            "A/5 1478",
            "A/5 21171",
            "A/5 21172",
            "A/5 21173",
            "A/5 21174",
            "A/5 21175",
            "A/5 2466",
            "A/5 2817",
            "A/5 3536",
            "A/5 3540",
            "A/5 3594",
            "A/5 3902",
            "A/5. 10482",
            "A/5. 13032",
            "A/5. 2151",
            "A/5. 3336",
            "A/5. 3337",
            "A/5. 851",
            "A/S 2816",
            "A4. 54510",
            "AQ/3. 30631",
            "AQ/4 3130",
            "C 17368",
            "C 17369",
            "C 4001",
            "C 7075",
            "C 7076",
            "C 7077",
            "C.A. 15185",
            "C.A. 17248",
            "C.A. 18723",
            "C.A. 2315",
            "C.A. 24579",
            "C.A. 24580",
            "C.A. 2673",
            "C.A. 29178",
            "C.A. 29395",
            "C.A. 29566",

INFO:root:API call to http://host.docker.internal:4100/dataset_schema/onebox/titanic succeeded.
Request response:   {
    "status": "SUCCESS",
    "result": {
      "dataset": {
        "name": "",
        "columns": [
          {
            "column-name": "pclass",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 1,
            "value-range-max": 3
          },
          {
            "column-name": "survived",
            "data-type": "category",
            "possible-values": [
              "0",
              "1"
            ],
            "is-nullable": false
          },
          {
            "column-name": "name",
            "data-type": "str",
            "is-nullable": false
          },
          {
            "column-name": "sex",
            "data-type": "category",
            "possible-values": [
              "female",
              "male"
            ],
            "is-nullable": false
          },
          {
            "column-name": "age",
            "data-type": "float",
            "is-nullable": true,
            "value-range-min": 0.1667,
            "value-range-max": 80.0
          },
          {
            "column-name": "sibsp",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 8
          },
          {
            "column-name": "parch",
            "data-type": "int",
            "is-nullable": false,
            "value-range-min": 0,
            "value-range-max": 9
          },
          {
            "column-name": "ticket",
            "data-type": "category",
            "possible-values": [
              "110152",
              "110413",
              "110465",
              "110469",
              "110489",
              "110564",
              "110813",
              "111163",
              "111240",
              "111320",
              "111361",
              "111369",
              "111426",
              "111427",
              "111428",
              "112050",
              "112051",
              "112052",
              "112053",
              "112058",
              "112059",
              "112277",
              "112377",
              "112378",
              "112379",
              "112901",
              "113028",

Request:
  url: http://host.docker.internal:4100/dataset_schema/onebox/titanic
  method: GET
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'data_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

ModelInfo:
  display_name: Titanic
  description: Predict likelihood of survival
  input_type: ModelInputType.TABULAR
  model_task: ModelTask.BINARY_CLASSIFICATION
  inputs:
           column     dtype count(possible_values) is_nullable    value_range
    0      pclass   INTEGER                              False      1 - 3
    1        name    STRING                              False
    2         sex  CATEGORY                      2       False
    3         age     FLOAT                               True  0.167 - 80.0
    4       sibsp   INTEGER                              False      0 - 8
    5       parch   INTEGER                              False      0 - 9
    6      ticket  CATEGORY                    929       False
    7        fare     FLOAT                               True    0.0 - 512.3
    8       cabin  CATEGORY                    186        True
    9    embarked  CATEGORY                      3        True
    10       boat  CATEGORY                     27        True
    11       body     FLOAT                               True    1.0 - 328.0
    12  home_dest  CATEGORY                    369        True
  outputs:
              column  dtype count(possible_values) is_nullable value_range
    0  probability_1  FLOAT                              False   0.0 - 1.0


  targets: [Column(name="survived", data_type=DataType.CATEGORY, possible_values=['0', '1'], is_nullable=False)]
  misc:
    {}

In [11]:
# We will train our classifier with the following features:
# Numeric Features:
# - age: float.
# - fare: float.
# Categorical Features:
# - embarked: categories encoded as strings {'C', 'S', 'Q'}.
# - sex: categories encoded as strings {'female', 'male'}.
# - pclass: ordinal integers {1, 2, 3}.

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV

# We create the preprocessing pipelines for both numeric and categorical data.
numeric_features = ['age', 'fare']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_features = ['embarked', 'sex', 'pclass']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression(solver='lbfgs'))])

X = df.drop('survived', axis=1)
y = df['survived']

# There is only one dataset for this example. So we are splitting it here
# User can also upload multiple files/sources to dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf.fit(X_train, y_train)
print("model score: %.3f" % clf.score(X_test, y_test))
clf.predict_proba(X_test)

model score: 0.800

array([[0.48026329, 0.51973671],
       [0.41187066, 0.58812934],
       [0.8591337 , 0.1408663 ],
       [0.817748  , 0.182252  ],
       [0.22813731, 0.77186269],
       [0.68326969, 0.31673031],
       [0.71531036, 0.28468964],
       [0.87557688, 0.12442312],
       [0.88247848, 0.11752152],
       [0.67565746, 0.32434254],
       [0.20506769, 0.79493231],
       [0.0647164 , 0.9352836 ],
       [0.20122417, 0.79877583],
       [0.65430119, 0.34569881],
       [0.15114149, 0.84885851],
       [0.80159693, 0.19840307],
       [0.89940104, 0.10059896],
       [0.20506769, 0.79493231],
       [0.74227832, 0.25772168],
       [0.93223619, 0.06776381],
       [0.56408912, 0.43591088],
       [0.78952137, 0.21047863],
       [0.19065299, 0.80934701],
       [0.87879119, 0.12120881],
       [0.85452056, 0.14547944],
       [0.51578967, 0.48421033],
       [0.90251969, 0.09748031],
       [0.56673092, 0.43326908],
       [0.69981674, 0.30018326],
       [0.10777727, 0.89222273],
       [0.89878334, 0.10121666],
       [0.08521331, 0.91478669],
       [0.57629525, 0.42370475],
       [0.67647122, 0.32352878],
       [0.10305264, 0.89694736],
       [0.91620448, 0.08379552],
       [0.89941577, 0.10058423],
       [0.90662324, 0.09337676],
       [0.54999124, 0.45000876],
       [0.90176953, 0.09823047],
       [0.11015178, 0.88984822],
       [0.73982487, 0.26017513],
       [0.82731452, 0.17268548],
       [0.14005779, 0.85994221],
       [0.11298788, 0.88701212],
       [0.90415833, 0.09584167],
       [0.19109856, 0.80890144],
       [0.85024065, 0.14975935],
       [0.87017043, 0.12982957],
       [0.5746162 , 0.4253838 ],
       [0.73553537, 0.26446463],
       [0.16888264, 0.83111736],
       [0.91686293, 0.08313707],
       [0.44648234, 0.55351766],
       [0.81053597, 0.18946403],
       [0.33577928, 0.66422072],
       [0.42854012, 0.57145988],
       [0.20592942, 0.79407058],
       [0.68160302, 0.31839698],
       [0.11017765, 0.88982235],
       [0.87509307, 0.12490693],
       [0.83892581, 0.16107419],
       [0.92529481, 0.07470519],
       [0.74037446, 0.25962554],
       [0.81007837, 0.18992163],
       [0.60970592, 0.39029408],
       [0.89825717, 0.10174283],
       [0.08553761, 0.91446239],
       [0.89926407, 0.10073593],
       [0.59137023, 0.40862977],
       [0.60167327, 0.39832673],
       [0.50491526, 0.49508474],
       [0.68339506, 0.31660494],
       [0.29238192, 0.70761808],
       [0.07617669, 0.92382331],
       [0.73304082, 0.26695918],
       [0.46292842, 0.53707158],
       [0.8452838 , 0.1547162 ],
       [0.10872239, 0.89127761],
       [0.71434652, 0.28565348],
       [0.21759566, 0.78240434],
       [0.16877849, 0.83122151],
       [0.93223619, 0.06776381],
       [0.15103187, 0.84896813],
       [0.75256237, 0.24743763],
       [0.93151727, 0.06848273],
       [0.92522823, 0.07477177],
       [0.69726032, 0.30273968],
       [0.88337166, 0.11662834],
       [0.88250311, 0.11749689],
       [0.91951995, 0.08048005],
       [0.92203638, 0.07796362],
       [0.05447843, 0.94552157],
       [0.84178526, 0.15821474],
       [0.15899498, 0.84100502],
       [0.89300558, 0.10699442],
       [0.71524746, 0.28475254],
       [0.90851013, 0.09148987],
       [0.35090463, 0.64909537],
       [0.77622114, 0.22377886],
       [0.08752253, 0.91247747],
       [0.7996013 , 0.2003987 ],
       [0.39232136, 0.60767864],
       [0.15671702, 0.84328298],
       [0.51578967, 0.48421033],
       [0.8588905 , 0.1411095 ],
       [0.52936842, 0.47063158],
       [0.85996946, 0.14003054],
       [0.89708701, 0.10291299],
       [0.75649447, 0.24350553],
       [0.45776875, 0.54223125],
       [0.67096627, 0.32903373],
       [0.73781491, 0.26218509],
       [0.35798538, 0.64201462],
       [0.78943364, 0.21056636],
       [0.38402049, 0.61597951],
       [0.04147107, 0.95852893],
       [0.14896328, 0.85103672],
       [0.79707767, 0.20292233],
       [0.77397723, 0.22602277],
       [0.35169045, 0.64830955],
       [0.55641045, 0.44358955],
       [0.15568076, 0.84431924],
       [0.93223619, 0.06776381],
       [0.68301491, 0.31698509],
       [0.86309304, 0.13690696],
       [0.41739299, 0.58260701],
       [0.57343534, 0.42656466],
       [0.09123523, 0.90876477],
       [0.89620925, 0.10379075],
       [0.16759707, 0.83240293],
       [0.24782493, 0.75217507],
       [0.93223619, 0.06776381],
       [0.41561519, 0.58438481],
       [0.57330623, 0.42669377],
       [0.66658195, 0.33341805],
       [0.34702215, 0.65297785],
       [0.14896328, 0.85103672],
       [0.87503008, 0.12496992],
       [0.90415833, 0.09584167],
       [0.57214382, 0.42785618],
       [0.12047374, 0.87952626],
       [0.85786393, 0.14213607],
       [0.36739701, 0.63260299],
       [0.88611121, 0.11388879],
       [0.84912502, 0.15087498],
       [0.71855216, 0.28144784],
       [0.13184814, 0.86815186],
       [0.75901343, 0.24098657],
       [0.82611721, 0.17388279],
       [0.7720324 , 0.2279676 ],
       [0.85473148, 0.14526852],
       [0.34315002, 0.65684998],
       [0.17788589, 0.82211411],
       [0.93996801, 0.06003199],
       [0.86005418, 0.13994582],
       [0.87485057, 0.12514943],
       [0.06840207, 0.93159793],
       [0.49171816, 0.50828184],
       [0.73304082, 0.26695918],
       [0.68963994, 0.31036006],
       [0.14803865, 0.85196135],
       [0.70217996, 0.29782004],
       [0.94557136, 0.05442864],
       [0.58311749, 0.41688251],
       [0.07290665, 0.92709335],
       [0.86420844, 0.13579156],
       [0.10014327, 0.89985673],
       [0.91953915, 0.08046085],
       [0.05441024, 0.94558976],
       [0.16021558, 0.83978442],
       [0.74649614, 0.25350386],
       [0.05948626, 0.94051374],
       [0.87506182, 0.12493818],
       [0.93418901, 0.06581099],
       [0.79955314, 0.20044686],
       [0.87407419, 0.12592581],
       [0.68020534, 0.31979466],
       [0.19647691, 0.80352309],
       [0.86005418, 0.13994582],
       [0.1800574 , 0.8199426 ],
       [0.91693096, 0.08306904],
       [0.83527713, 0.16472287],
       [0.76393707, 0.23606293],
       [0.77397723, 0.22602277],
       [0.36568134, 0.63431866],
       [0.93222757, 0.06777243],
       [0.06304059, 0.93695941],
       [0.92036533, 0.07963467],
       [0.83707434, 0.16292566],
       [0.22362011, 0.77637989],
       [0.58365939, 0.41634061],
       [0.03442288, 0.96557712],
       [0.06789046, 0.93210954],
       [0.32076266, 0.67923734],
       [0.5683929 , 0.4316071 ],
       [0.69831914, 0.30168086],
       [0.16879302, 0.83120698],
       [0.19942855, 0.80057145],
       [0.4325691 , 0.5674309 ]])

In [6]:
import pathlib
import shutil
import pickle
import yaml

# create temp dir
model_dir = pathlib.Path(model_id)
shutil.rmtree(model_dir, ignore_errors=True)
model_dir.mkdir()

# save model
with open(model_dir / 'model.pkl', 'wb') as pkl_file:
    pickle.dump(clf, pkl_file)

# save model schema
with open(model_dir / 'model.yaml', 'w') as yaml_file:
    yaml.dump({'model': model_info.to_dict()}, yaml_file)

In [7]:
%%writefile titanic/package.py

import pickle
from pathlib import Path
import pandas as pd

PACKAGE_PATH = Path(__file__).parent

class SklearnModelPackage:
    is_classifier = True
    output_columns = ['survived']

    def __init__(self):
        with open(PACKAGE_PATH / 'model.pkl', 'rb') as infile:
            self.model = pickle.load(infile)

    def predict(self, input_df):
        f = self.model.predict if not self.is_classifier else self.model.predict_proba
        return pd.DataFrame(f(input_df), columns=self.output_columns)
    
def get_model():
    return SklearnModelPackage()

Writing titanic/package.py

In [8]:
client.delete_model(project_id, model_id)
client.upload_model_package(model_dir, project_id, model_id)

In [7]:
client.verbose = True
prediction_input = train_input[0: 10]
prediction_input = prediction_input[['age', 'fare', 'embarked', 'sex', 'pclass']]
prediction_input.describe
prediction_input['age'] = prediction_input['age'].astype(float)
prediction_input['fare'] = prediction_input['fare'].astype(float)
result = client.run_model(project_id, model_id, prediction_input, log_events=False)
result

# data_array = [y.iloc[0,:].to_dict() for x , y in prediction_input.groupby(level=0)]
# print(data_array)

# payload = dict(
#             project_id=project_id,
#             model_id=model_id,
#             data=data_array,
#             logging=False,
#         )
# import json
# json.dumps(payload)

INFO:root:running api call as POST request
to http://host.docker.internal:4100/v1/execution/run/onebox
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "project_id": "tutorial",
    "model_id": "titanic",
    "data": [
      {
        "age": 29.0,
        "fare": 211.3375,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 0.9167,
        "fare": 151.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 2.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 30.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 25.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 48.0,
        "fare": 26.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 63.0,
        "fare": 77.9583,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 39.0,
        "fare": 0.0,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 53.0,
        "fare": 51.4792,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 71.0,
        "fare": 49.5042,
        "embarked": "C",
        "sex": "male",
        "pclass": 1
      }
    ],
    "logging": false
  }
DEBUG:root:Request:
  url: http://host.docker.internal:4100/v1/execution/run/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'executor_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '849'}
DEBUG:urllib3.connectionpool:Resetting dropped connection: host.docker.internal
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /v1/execution/run/onebox HTTP/1.1" 400 119
INFO:root:response: {
    "errors": {
        "": "None is not of type 'object'"
    },
    "message": "Input payload validation failed"
}

DEBUG:root:API call failed.
Error message: Input payload validation failed
Endpoint: http://host.docker.internal:4100/v1/execution/run/onebox
Request:
  url: http://host.docker.internal:4100/v1/execution/run/onebox
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'executor_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '849'}
INFO:root:running api call as POST request
to http://host.docker.internal:4100/execute/onebox/tutorial/titanic
with headers {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c'}
with payload   {
    "data": [
      {
        "age": 29.0,
        "fare": 211.3375,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 0.9167,
        "fare": 151.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 2.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 30.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 25.0,
        "fare": 151.55,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 48.0,
        "fare": 26.55,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 63.0,
        "fare": 77.9583,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 39.0,
        "fare": 0.0,
        "embarked": "S",
        "sex": "male",
        "pclass": 1
      },
      {
        "age": 53.0,
        "fare": 51.4792,
        "embarked": "S",
        "sex": "female",
        "pclass": 1
      },
      {
        "age": 71.0,
        "fare": 49.5042,
        "embarked": "C",
        "sex": "male",
        "pclass": 1
      }
    ],
    "logging": false
  }
DEBUG:root:Request:
  url: http://host.docker.internal:4100/execute/onebox/tutorial/titanic
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'executor_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '800'}
DEBUG:urllib3.connectionpool:http://host.docker.internal:4100 "POST /execute/onebox/tutorial/titanic HTTP/1.1" 500 461
INFO:root:response: {
  "message": "argument of type 'NoneType' is not iterable",
  "stacktrace": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/fiddler_utils/web_service.py\", line 101, in new_function\n    result = original_function(*args, **kwargs)\n  File \"/app/executor/service.py\", line 80, in execute_endpoint\n    if DATA_KEY not in request.json:\nTypeError: argument of type 'NoneType' is not iterable\n",
  "status": "FAILURE"
}

DEBUG:root:API call failed.
Error message: argument of type 'NoneType' is not iterable
Endpoint: http://host.docker.internal:4100/execute/onebox/tutorial/titanic
Stacktrace: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/fiddler_utils/web_service.py", line 101, in new_function
    result = original_function(*args, **kwargs)
  File "/app/executor/service.py", line 80, in execute_endpoint
    if DATA_KEY not in request.json:
TypeError: argument of type 'NoneType' is not iterable

Request:
  url: http://host.docker.internal:4100/execute/onebox/tutorial/titanic
  method: POST
  headers: {'Authorization': 'Bearer Sxcg0eCz8aJKUXnrAMOB6EQ8FUuS-hgZvqlQXg-0R6c', 'x-fdlr-fwd': 'executor_service', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '800'}

RuntimeError: API call failed.
Error message: argument of type 'NoneType' is not iterable
Endpoint: http://host.docker.internal:4100/execute/onebox/tutorial/titanic
Stacktrace: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/fiddler_utils/web_service.py", line 101, in new_function
    result = original_function(*args, **kwargs)
  File "/app/executor/service.py", line 80, in execute_endpoint
    if DATA_KEY not in request.json:
TypeError: argument of type 'NoneType' is not iterable